[package]
name = "lencode"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A crate for encoding and decoding variable-length data using an optimal LEB128 lencoding scheme"
keywords = ["encoding", "decoding", "bincode", "leb128", "serde"]
authors = ["sam0x17"]
repository = "https://github.com/sam0x17/lencode"
documentation = "https://docs.rs/lencode/latest/lencode/"

[dependencies]
serde = { version = "1", optional = true }

[dev-dependencies]
rayon = "1"

[features]
default = ["std", "serde"]
std = []
serde = ["dep:serde"]

[profile.test]
opt-level = 3

[profile.dev]
opt-level = 3
