[package]
name = "lencode"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A crate for encoding and decoding variable-length data using an optimal LEB128 lencoding scheme"
keywords = ["encoding", "decoding", "bincode", "leb128", "serde"]
authors = ["sam0x17"]
repository = "https://github.com/sam0x17/lencode"
documentation = "https://docs.rs/lencode/latest/lencode/"

[dependencies]
bitvec = "1"
endian-cast = "2"
serde = { version = "1", optional = true, default-features = false, features = ["derive"] }
typenum = "1"
generic-array = "1"

[dev-dependencies]
rayon = "1"

[features]
default = ["std"]
std = ["serde/std"]

[profile.test]
opt-level = 3
lto = true

[profile.dev]
opt-level = 3
lto = true

[profile.release]
opt-level = 3
lto = true
