name: CI Checks
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  cargo-test:
    name: cargo test (little endian)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo test
        run: cargo test --workspace
  cargo-test-all-features:
    name: cargo test (little endian, all features)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo test
        run: cargo test --workspace --all-features
  cargo-fmt:
    name: cargo fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo fmt
        run: cargo fmt -- --check
  cargo-clippy:
    name: cargo clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo clippy
        run: cargo clippy --workspace --all-features -- -D warnings
  cargo-doc:
    name: cargo doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cargo doc
        run: cargo doc --workspace --all-features
